# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.3.1.dev2+g25bc91a.d20230221'
__version_tuple__ = version_tuple = (0, 3, 1, 'dev2', 'g25bc91a.d20230221')
