# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.2.dev1+gc839b04.d20230207'
__version_tuple__ = version_tuple = (0, 2, 2, 'dev1', 'gc839b04.d20230207')
