# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.1.dev0+gc82fa94.d20230206'
__version_tuple__ = version_tuple = (0, 2, 1, 'dev0', 'gc82fa94.d20230206')
